global proc CreateToolbox() {
    string $mWindow = "myTooBox";
    
    if(`window -exists $mWindow`)
    deleteUI -window $mWindow;
    
    
    $mWindow = `window $mWindow`;
    $mColLayout = `columnLayout -parent $mWindow`;
    $ctrlBtn = `button -label "Controls" -c "ControlBtn()"`;
    
    showWindow($mWindow);
    
}
global proc ControlsBtn() {
    source myControls;
    ControlWindow();
    
}

CreateToolbox();